// 拡張する時に見やすい書きやすいようにこのファイルにまとめる

const PostActionTypes = {
  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
  FETCHING_POSTS: 'FETCHING_POSTS',
  FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
  ADDING_POST: 'ADDING_POST',
  ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
  ADD_POST_FAILURE: 'ADD_POST_FAILURE',
  FETCH_POST_SUCCESS: 'FETCH_POST_SUCCESS',
  FETCHING_POST: 'FETCHING_POST',
  FETCH_POST_FAILURE: 'FETCH_POST_FAILURE',
  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
  UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS'
}

export default PostActionTypes