const PostActionTypes = {
  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
  IS_FETCHING_POSTS: 'IS_FETCHING_POSTS',
  FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
  IS_ADDING_POST: 'IS_ADDING_POST',
  ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
  ADD_POST_FAILURE: 'ADD_POST_FAILURE',
  FETCH_POST_SUCCESS: 'FETCH_POST_SUCCESS',
  IS_FETCHING_POST: 'IS_FETCHING_POST',
  FETCH_POST_FAILURE: 'FETCH_POST_FAILURE',
  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
  UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS'
}

export default PostActionTypes